dist: xenial
language: php

php:
  - 8.0

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer install --prefer-dist --no-interaction --no-suggest

script: vendor/bin/phpunit
